"use strict";
console.log(3
    + 3);
    // alert(3 + 3); this is not a correct way of writing code
/// FOLLOW TC39 AND MDN  DOCUMENTATION
let name = "aarush";
let age = 20;
let isLoggedIn = false;
let state;
let ststi = null;

// number=> 2 to power 53
// bigint 
// string=> ""
// boolean => true/false;
// null => standolane value
// undefined => value is not assigned;
// symbol=> is used to find the uniqueness 
// object


console.log(typeof name);  // TYPE OF NAME IS STRTING AND TYPE OF NULL IS OBJECT
// TYPE OF AGE IS NUMBER
// TYPE OF UNDEFINED IS UNDEFINED
// TYPE OF AGE IS NUMBER

console.log(typeof age);
console.log(typeof null);
